# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
