# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='one_who_pokes',
        ),
    ]
