# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_user_pokehistory'),
        ('belt', '0002_remove_poke_one_who_pokes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='one_poking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='first_app.User'),
        ),
        migrations.AlterField(
            model_name='poke',
            name='one_getting_poked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokee', to='first_app.User'),
        ),
    ]
